resource_group_name   = "rg-compute-demo"
//vm_name               = "myvm"
//vm_size               = "Standard_B1s"
admin_username        = "azureuser"
ssh_public_key_path   = "C:/Users/MadhaviSingh/.ssh/id_rsa.pub"
subnet_id             = "/subscriptions/ab767c69-dd43-4c09-8d42-2b2493036b43/resourceGroups/rg-network-demo/providers/Microsoft.Network/virtualNetworks/demo-vnet/subnets/demo-subnet"
//location              = "East US"
